config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  namespace :api do
    namespace :v1 do
      get 'posts', to: 'posts#index'
      get 'posts/:post_id', to: 'posts#show'
      post 'posts', to: 'posts#create'
      post 'authenticate', to: 'sessions#create'
      post 'reports/by_author', to: 'reports#by_author'
    end
  end

  resources :user_sessions
  resources :users
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get 'login' => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Authority::Abilities

  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  include Authority::Abilities

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Authority::Abilities
  include Authority::UserAbilities

  authenticates_with_sorcery!

  has_many :posts
  has_many :comments
  has_one_attached :avatar

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, presence: true,
                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i },
                    uniqueness: { case_sensitive: false }
  validates :nickname, presence: true
  validates :avatar, blob: { content_type: ['image/png', 'image/jpg'], size_range: 0..3.megabytes }
end

app/controllers/api/v1/base_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class BaseController < ApplicationController
      protect_from_forgery with: :null_session
      skip_before_action :require_login

      def current_user
        @current_user ||= Jwt::UserAuthenticator.call(request.headers)
      end

      def authenticate
        render json: { errors: 'Unauthorized' }, status: :unauthorized unless current_user
      end
    end
  end
end

app/controllers/api/v1/posts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class PostsController < BaseController
      before_action :authenticate

      def show
        render json: Post.find(params[:post_id])
      end

      def index
        add_headers
        render json: Post.page(params[:page]).per(page_limit).order(published_at: :desc)
      end

      def create
        post = Post.create! post_params
        render json: post
      rescue ActiveRecord::RecordInvalid => e
        render json: { errors: e.message.partition('Validation failed: ').last.split(', ') }, status: :unprocessable_entity
      end

      private

      def page_limit
        @page_limit ||= params[:per_page] || Post.default_per_page
      end

      def post_params
        { title: params[:title], body: params[:body], user: current_user, published_at: params[:published_at] || Time.now }
      end

      def add_headers
        response.headers['Total-pages'] = (Post.count / page_limit.to_f).ceil
        response.headers['Total-records'] = Post.count
      end
    end
  end
end

app/controllers/api/v1/reports_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ReportsController < BaseController
      def by_author
        return render json: { errors: 'Unauthorized' }, status: :unauthorized unless current_user
        return render json: { error: missing_params }, status: :unprocessable_entity unless missing_params.empty?

        render json: { message: 'Report generation started' }
        ReportGenerationJob.perform_later(params[:start_date], params[:end_date], params[:email])
      end

      private

      def missing_params
        %w[start_date end_date email] - params.keys
      end
    end
  end
end

app/controllers/api/v1/sessions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class SessionsController < BaseController
      def create
        user = User.authenticate(params[:email], params[:password])

        if user
          token = Jwt::TokenProvider.call(user_id: user.id)
          render json: { user: user, token: token }
        else
          render json: { error: 'Invalid email or password.' }, status: :unauthorized
        end
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    post.comments.create! permitted_params.merge(user_id: current_user.id)
    redirect_to post_path(post), alert: 'Комментарий создан.'
  rescue ActiveRecord::RecordInvalid => e
    redirect_to post_path(post), alert: e.message
  end

  def destroy
    authorize_action_for comment
    comment.destroy!
    redirect_to post_path(post), alert: 'Комментарий удален.'
  rescue ActiveRecord::RecordInvalid => e
    redirect_to post_path(post), alert: e.message
  end

  private

  def post
    @post ||= Post.find params[:post_id]
  end

  def comment
    post.comments.find(params[:id])
  end

  def permitted_params
    params.require(:comment).permit(:body, :published_at)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def index
    render :index, locals: { posts: Post.order(published_at: :desc).page(params[:page]) }
  end

  def new
    render :new, locals: { post: Post.new }
  end

  def show
    render locals: { post: post, comments: post.comments.order(published_at: :desc).page(params[:page]) }
  end

  def edit
    render :edit, locals: { post: post }
  end

  def create
    Post.create! permitted_params.merge(user_id: current_user.id)
    redirect_to posts_path, alert: 'Пост создан.'
  rescue ActiveRecord::RecordInvalid => e
    render :new, locals: { post: e.record }, alert: e.message
  end

  def update
    authorize_action_for post
    post.update! permitted_params
    redirect_to posts_path, alert: 'Пост изменен.'
  rescue ActiveRecord::RecordInvalid => e
    render :edit, locals: { post: e.record }, alert: e.message
  end

  def destroy
    authorize_action_for post
    post.destroy!
    redirect_to posts_path, alert: 'Пост удален.'
  rescue ActiveRecord::RecordInvalid => e
    redirect_to posts_path, alert: e.message
  end

  private

  def post
    @post ||= Post.find params[:id]
  end

  def permitted_params
    params.require(:post).permit(:title, :body, :published_at)
  end
end

app/controllers/user_sessions_controller.rb
# frozen_string_literal: true

class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    render :new, locals: { user: User.new }
  end

  def create
    if login user_params[:email], user_params[:password]
      redirect_back_or_to root_path, alert: 'Добро пожаловать!'
    else
      flash.now.alert = 'Неверный email или пароль.'
      new
    end
  end

  def destroy
    logout
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    render locals: { user: User.new }
  end

  def edit
    render :edit, locals: { user: current_user }
  end

  def create
    auto_login User.create!(user_params)
    redirect_to root_path
  rescue ActiveRecord::RecordInvalid => e
    flash.now.alert = e.message
    render :new, locals: { user: e.record }
  end

  def update
    current_user.update(user_params)
    redirect_to edit_user_path(current_user), alert: message
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :avatar)
  end

  def message
    current_user.errors.full_messages.join(', ').presence || 'Профиль изменен.'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.slim
| Добро пожаловать #{current_user.nickname}

app/views/layouts/application.slim
doctype html
html
  head
    title Blog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      nav.navbar.fixed-top.navbar-expand-sm.navbar-dark.bg-primary  
        button.navbar-toggler[type="button" data-toggle="collapse" data-target="#collapsingNavbarLg"]
          span.navbar-toggler-icon
        #collapsingNavbarLg.navbar-collapse.collapse
          ul.navbar-nav
            - if current_user
              li.nav-item
                = link_to current_user.nickname, edit_user_path(current_user), class: 'nav-link'
              li.nav-item
                = link_to 'Посты', posts_path, class: 'nav-link'
              li.nav-item
                = link_to 'Выход', logout_path, method: :delete, class: 'nav-link'
            - else
              li.nav-item
                = link_to 'Вход', login_path, class: 'nav-link'
              li.nav-item
                = link_to 'Регистрация', new_user_path, class: 'nav-link'
      br
      p.notice= notice
      p.alert= alert
      = yield

app/views/posts/_actions.slim
- if post.updatable_by?(current_user)
  hr
  = link_to 'Редактировать', edit_post_path(post), class: 'btn btn-success'
  hr
  = link_to 'Удалить', post_path(post), method: :delete, data: { confirm: 'Удалить?' }, class: 'btn btn-danger btn-sm'

app/views/posts/_comments.slim
h4 Комментарии:
table.table.table-condensed.table-striped
  thead
    tr
      th Body
      th Author
      th Published at:
      th Действия
  tbody
    - comments.each do |comment|
      tr
        td[width='50%']= comment.body
        td= comment.user.nickname
        td= comment.published_at
        td
          - if comment.deletable_by?(current_user)
            = link_to 'Удалить', post_comment_path(comment.post, comment), method: :delete, data: { confirm: 'Удалить?' }, class: 'btn btn-danger btn-sm'

app/views/posts/_form.slim
= simple_form_for post do |f|
  .row
    .col-md-12
      = f.input :title, as: :string
      = f.input :body, as: :text
      = f.input :published_at, as: :datetime
  hr
  = f.button :submit, 'Создать/изменить', class: 'btn btn-success'

app/views/posts/_posts.slim
table.table.table-condensed.table-striped
  thead
    tr
      th Title
      th Body
      th Author
      th Published at:
      th Действия
  tbody
    - posts.each do |post|
      tr
        td= post.title
        td[width='50%']= post.body
        td
          - if post.user.avatar.attached?
            = image_tag post.user.avatar.variant(resize: '80x80')
          br
          = post.user.nickname
        td= post.published_at
        td
          = link_to 'Показать', post_path(post), class: 'btn btn-success'
          = render 'actions', post: post

app/views/posts/edit.slim
h1 Редактировать пост

= render 'form', post: post

app/views/posts/index.slim
h2 Посты:
.text-right
  = link_to 'Новый пост', new_post_path, class: 'btn btn-success'
br
- if posts.any?
  = paginate posts, theme: 'twitter-bootstrap-4'
  = render 'posts', posts: posts
  = paginate posts, theme: 'twitter-bootstrap-4'
- else
  p.alert Посты отсутствуют

app/views/posts/new.slim
h1 Создать пост

= render 'form', post: post

app/views/posts/show.slim
h3 Пост:
table.table.table-condensed.table-striped
  thead
    tr
      th Title
      th Body
      th Author
      th Published at:
      th Действия
  tbody
    tr
      td= post.title
      td[width='50%']= post.body
      td
        - if post.user.avatar.attached?
          = image_tag post.user.avatar.variant(resize: '80x80')
        br
        = post.user.nickname
      td= post.published_at
      td
        = render 'posts/actions', post: post
h4 Добавить комментарий:
= simple_form_for [ post, post.comments.build ] do |f|
  = f.input :body, as: :text
  = f.input :published_at, as: :datetime
  hr
  .text-right
    = f.button :submit, 'Создать', class: 'btn btn-success'
br
- if comments.any?
  = paginate comments, theme: 'twitter-bootstrap-4'
  = render 'posts/comments', comments: comments
  = paginate comments, theme: 'twitter-bootstrap-4'
- else
  p.alert Комментарии отсутствуют

app/views/user_sessions/_form.slim
= simple_form_for(user, method: :post, url: user_sessions_path) do |f|
  .row
    .col-md-6
      = f.input :email, as: :string
    .col-md-6
      = f.input :password
  hr
  = f.button :submit, 'Войти', class: 'btn btn-success'

app/views/user_sessions/new.slim
h1 Войдите
hr
= render 'form', user: user

app/views/users/_form.slim
= simple_form_for user do |f|
  .row
    .col-md-6
      = f.input :email, as: :string
      = f.input :password
    .col-md-6
      = f.input :nickname, as: :string
      = f.input :password_confirmation
  .row
    .col-md-6
      - if user.avatar.attached?
        = f.label :avatar
        br
        = image_tag user.avatar.variant(resize: '300x300')
    .col-md-6
      br
      = f.file_field :avatar
  hr
  = f.button :submit, 'Создать/изменить', class: 'btn btn-success'

app/views/users/edit.slim
h1 Редактировать профиль

= render 'form', user: user

app/views/users/new.slim
h1 Новый пользователь

= render 'form', user: user